
import { Inter } from 'next/font/google'
import './globals.css'
import { AuthContextProvider } from './context/authcontext'
import Navbar from './components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}){
  return (
    <html lang="en" className='bg-[#fff] text-[#000]'>
      <body className={inter.className}>
        <AuthContextProvider>
          <Navbar/>
          {children}
        </AuthContextProvider>
      </body>
    </html>
  )
}
